version: 0.2

run-as: root

env:
  exported_variables:
    - MIX_ENV=test

phases:
  install:
    commands:
      - export MIX_ENV=test
      - apt-get update
      -	sh -c 'echo exit 0 > /usr/sbin/policy-rc.d'
      - adduser ubuntu
      - ls -l /home
      - apt-get -y install netcat
      - apt-get -y install postgresql postgresql-contrib
      - cat /usr/sbin/policy-rc.d
      - nc -v localhost 5432
  build:
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile gettext
      - mix format --check-formatted --dry-run --check-equivalent
      - mix credo
      - mix do ecto.create, ecto.migrate
      - mix coveralls.html

