version: 0.2

run-as: root

env:
  exported_variables:
    - MIX_ENV=test

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install wget ca-certificates
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - apt-get update
      - apt-get -y install postgresql postgresql-contrib
      - apt-get -y install xfonts-base xfonts-75dpi
      - wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
      - dpkg -i wkhtmltox_0.12.5-1.xenial_amd64.deb | apt-get -y -f install
      - service redis-server restart
  build:
    commands:
      - mix format --check-formatted --dry-run --check-equivalent
      - mix credo
      - mix coveralls.html

