version: 0.2
  
run-as: ubuntu

env:
  exported_variables:
    - MIX_ENV=test

phases:
  install:
    commands:
      - runuser -l root -c 'export MIX_ENV=test'
      - sudo apt-get update
      - sudo sh -c 'echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d'
      - sudo apt-get -y install postgresql postgresql-contrib
      - apt-get -y install xfonts-base xfonts-75dpi
      - apt-get -y install wkhtmltopdf
      - apt-get -y install redis-server
      - service redis-server restart
      - wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && dpkg -i erlang-solutions_2.0_all.deb
      - apt-get update
      - apt-get -y install esl-erlang
      - apt-get -y install erlang-dev
      - apt-get -y install erlang-parsetools
      - apt-get -y install elixir
      - mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.1/phoenix_new-0.13.1.ez
      - apt-get -y install erlang-crypto
  build:
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile gettext
      - mix format --check-formatted --dry-run --check-equivalent
      - mix credo
      - mix do ecto.create, ecto.migrate
      - mix coveralls.html
