version: 0.2

run-as: root

env:
  exported_variables:
    - MIX_ENV=test

phases:
  install:
    commands:
      - export MIX_ENV=test
      - apt-get update
      - adduser ubuntu
      - ls -l /home
      - apt-get -y install wget ca-certificates
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - apt-get -y install postgresql postgresql-contrib
      - runuser -l ubuntu '/usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start'
      - apt-get -y install xfonts-base xfonts-75dpi
      - apt-get -y install wkhtmltopdf
      - apt-get -y install redis-server
      - service redis-server restart
      - wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && dpkg -i erlang-solutions_2.0_all.deb
      - apt-get update
      - apt-get -y install esl-erlang
      - apt-get -y install erlang-dev
      - apt-get -y install erlang-parsetools
      - apt-get -y install elixir
      - mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.1/phoenix_new-0.13.1.ez
      - apt-get -y install erlang-crypto  
  build:
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile gettext
      - mix format --check-formatted --dry-run --check-equivalent
      - mix credo
      - mix do ecto.create, ecto.migrate
      - mix coveralls.html

