version: 0.2

run-as: root

env:
  exported_variables:
    - MIX_ENV=test

phases:
  install:
    commands:
      - export MIX_ENV=test
      - wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && dpkg -i erlang-solutions_2.0_all.deb
      - apt-get update
      - apt-get -y install esl-erlang
      - apt-get -y install elixir
      - apt-get -y install erlang-parsetools
      - apt-get -y install erlang-dev
      - mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.1/phoenix_new-0.13.1.ez
      - apt-get -y install erlang-crypto
  build:
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile gettext
      - mix format --check-formatted --dry-run --check-equivalent
      - mix credo
      - mix coveralls.html

