version: 0.2

run-as: root

env:
  exported_variables:
    - MIX_ENV=test

phases:
  install:
    commands:
      - apt-get update
      - apt-get --yes remove postgresql\*
      - apt-get install -y postgresql-11 postgresql-client-11
      - cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
      - service postgresql restart 11
      - apt-get -y install xfonts-base xfonts-75dpi
      - wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
      - dpkg -i wkhtmltox_0.12.5-1.xenial_amd64.deb
      - service redis-server restart
  build:
    commands:
      - mix format --check-formatted --dry-run --check-equivalent
      - mix credo
      - mix coveralls.html

